sudo: false
language: java
jdk:
  - oraclejdk8

branches:
  - master
  - develop

install:
  - mvn clean install

script:
  - mvn cobertura:cobertura coveralls:report

cache:
  directories:
  - $HOME/.m2

deploy:
  provider: script
  script: "[[ $TRAVIS_BRANCH == \"master\" ]] || [[ $TRAVIS_BRANCH == \"develop\" ]] && mvn -s .m2/settings.xml deploy"
  skip_cleanup: true
