sudo: false
language: java
jdk:
  - oraclejdk8

script:
  - mvn clean install cobertura:cobertura coveralls:report

cache:
  directories:
  - $HOME/.m2

deploy:
  provider: script
  script: "mvn -s .ci/settings.xml deploy -DskipTests -B"
  skip_cleanup: true
  on:
    branch:
      - master
      - develop
